"""Module 1: Hello World Application"""

cc_binary(
    name = "hello_world",
    srcs = ["hello_world.cpp"],
    copts = [
        "-Wall",
        "-Wextra",
    ],
    visibility = ["//visibility:public"],
)
