# module_4/src/BUILD
# Build file for QNX Security Policies and Access Control module

cc_binary(
    name = "receiver",
    srcs = ["receiver.cpp"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "sender1",
    srcs = ["sender1.cpp"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "sender2",
    srcs = ["sender2.cpp"],
    visibility = ["//visibility:public"],
)
