filegroup(
    name = "ipc_build",
    srcs = ["ipc.build"],
    visibility = [
        "//03_ipc:__pkg__"
    ],
)

filegroup(
    name = "ipc_secure_build",
    srcs = ["ipc_secure.build"],
    visibility = [
        "//03_ipc:__pkg__"
    ],
)
