cc_binary(
    name = "sender_a",
    srcs = ["sender_a.cpp"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sender_a_secpol",
    srcs = ["sender_a.secpol"],
    visibility = ["//visibility:public"],
)