# src/BUILD

cc_binary(
    name = "receiver",
    srcs = ["receiver.cpp"],
    copts = ["-Wall", "-Wextra", "-std=c++14"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "sender1",
    srcs = ["sender1.cpp"],
    copts = ["-Wall", "-Wextra", "-std=c++14"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "sender2",
    srcs = ["sender2.cpp"],
    copts = ["-Wall", "-Wextra", "-std=c++14"],
    visibility = ["//visibility:public"],
)
