cc_binary(
    name = "sender_b",
    srcs = ["sender_b.cpp"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sender_b_secpol",
    srcs = ["sender_b.secpol"],
    visibility = ["//visibility:public"],
)
