cc_binary(
    name = "receiver",
    srcs = ["receiver.cpp"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "receiver_secpol",
    srcs = ["receiver.secpol"],
    visibility = ["//visibility:public"],
)